[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.build]
dependsOn = ["install"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.start]
cmd = "python app.py"

providers = ["python"] 