[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
AUTO_INIT_DB = "false"
DB_SCHEMA_FILE = "database_schema.sql"
DB_SEED_FILE = "seed_data.sql"
CETEC_API_KEY = ""
CETEC_API_URL = ""
APP_ENV = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
SECRET_KEY = "your-secret-key-change-in-production"
API_KEY = "your-api-key-change-in-production" 